---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  replicas: 4
  revisionHistoryLimit: 5
