apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
namespace: my-first-openshift-prod

images:
  - name: image-registry.openshift-image-registry.svc:5000/my-first-openshift-common/book-inventory:latest
    newName: image-registry.openshift-image-registry.svc:5000/my-first-openshift-common/book-inventory
    newTag: latest
  - name: nginx:1.14.2
    newName: nginx
    newTag: 1.14.2

resources:
- ../../base

patchesStrategicMerge:
- book-inventory.yaml
- web.yaml
- postgres.yaml
