# Allows pulls from internal registry.
# means: oc policy add-role-to-user system:image-puller system:serviceaccount:my-first-openshift-dev:default -n my-first-openshift-dev
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller-common
  namespace: my-first-openshift-common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-first-openshift-dev
- kind: ServiceAccount
  name: default
  namespace: my-first-openshift-stg
- kind: ServiceAccount
  name: default
  namespace: my-first-openshift-prod
