apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: dev
  app.kubernetes.io/managed-by: kustomize
namespace: my-first-openshift-dev

resources:
- ../../base

patchesStrategicMerge:
- service-a.yaml
