---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
