apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
  namespace: my-first-openshift-common
spec:
  type: git
  params:
    - name: url
      value: https://github.com/tarosaiba/my-first-openshift-service-a.git
    - name: revision
      value: master

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-registry
spec:
  type: image
  params:
    - name: url
      value: "image-registry.openshift-image-registry.svc:5000/my-first-openshift-common/service-a"
