apiVersion: tekton.dev/v1beta1

kind: Pipeline
metadata:
  name: ci-pipeline-services
  namespace: my-first-openshift-common
spec:
  resources:
    - name: appSource
      type: git
    - name: appImage
      type: image
  tasks:
    - name: build-and-push-app
      taskRef:
        name: build-and-push-app
      params:
        - name: contextDir
          value: "."
      resources:
        inputs:
          - name: source
            resource: appSource
        outputs:
          - name: builtImage
            resource: appImage
