---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-service-a
  namespace: my-first-openshift-common
spec:
  type: git
  params:
    - name: url
      value: https://github.com/tarosaiba/my-first-openshift-service-a.git
    - name: revision
      value: master

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-service-b
  namespace: my-first-openshift-common
spec:
  type: git
  params:
    - name: url
      value: https://github.com/tarosaiba/my-first-openshift-service-b.git
    - name: revision
      value: master
