##################################################################################################
# My Service B
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: book-review
  labels:
    app: book-review
    role: backend
    service: book-review
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: book-review
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review
  labels:
    app: book-review
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-review
  template:
    metadata:
      labels:
        app: book-review
        role: backend
    spec:
      containers:
      - name: book-review
        image: image-registry.openshift-image-registry.svc:5000/my-first-openshift-common/book-review:master
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mongo"
        - name: DB_NAME
          value: "bezkoder_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: database-password
      serviceAccountName: privileged-app
