##################################################################################################
# My Service A
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: book-inventory
  labels:
    app: book-inventory
    role: backend
    service: book-inventory
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: book-inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-inventory
  labels:
    app: book-inventory
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-inventory
  template:
    metadata:
      labels:
        app: book-inventory
        role: backend
    spec:
      containers:
      - name: book-inventory
        image: image-registry.openshift-image-registry.svc:5000/my-first-openshift-common/book-inventory:master
        ports:
        - containerPort: 8080
        env:
        - name: GOCACHE
          value: "/tmp"
        - name: PORT
          value: "8080"
        - name: PG_HOST
          value: "postgres"
        - name: PG_PORT
          value: "5432"
        - name: PG_DB
          value: "book-inventory"
        - name: PG_USER
          value: "user-a"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database-password
      serviceAccountName: privileged-app
