##################################################################################################
# My Service B
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    role: backend
    service: service-a
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        role: backend
    spec:
      containers:
      - name: service-a
        image: image-registry.openshift-image-registry.svc:5000/my-first-openshift-common/service-a:master
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mongo"
        - name: DB_NAME
          value: "bezkoder_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: database-password
      serviceAccountName: privileged-app
