apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - network-policy.yaml
  - lb.yaml
  - book-inventory.yaml
  - postgres.yaml
  - book-review.yaml
  - mongo.yaml
  - web.yaml
  - loadtest.yaml
