kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: lb-api
  labels:
    app: service-a
    service: service-a
spec:
  to:
    kind: Service
    name: service-a
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: lb-api-b
  labels:
    app: service-b
    service: service-b
spec:
  to:
    kind: Service
    name: service-b
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
