---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
stringData:
  database-password: P@assw0rd!

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - name: mongo
    nodePort: 0
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: docker.io/mongo:5.0.2
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
        - name: MONGODB_DATABASE
          value: bezkoder_db
        - name: MONGODB_USER
          value: root
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongo
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo
