##################################################################################################
# My Service A
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    service: service-a
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: image-registry.openshift-image-registry.svc:5000/my-first-openshift/service-a:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOCACHE
          value: "/tmp"
        - name: PORT
          value: "8080"
        - name: PG_HOST
          value: "cluster-sample-rw"
        - name: PG_USER
          value: "app"
        - name: PG_PASSWORD
          value: "kK2lfO6EKkVDJwkWgUZ4kGyIyXS3z30Etwc0QvHfgMYxzjxVpCmbpb1hoy5s3QuG"
        - name: PG_PORT
          value: "5432"
        - name: PG_DB
          value: "app"
