apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: image-registry.openshift-image-registry.svc:5000/my-first-openshift/service-a:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOCACHE
          value: "/tmp"
        - name: PORT
          value: "8080"
        - name: PG_USER
          value: "postgres"
        - name: PG_PASSWORD
          value: "postgres"
        - name: PG_PORT
          value: "5432"
        - name: PG_DB
          value: "tasks"
