apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app
  namespace: my-first-openshift-common
spec:
  workspaces:
  - name: app-code
    description: Git Repo for Apps
  - name: vul-cache
    description: Cache vulnerabilities infomations
  params:
  - name: target-app
    type: string
    description: Target application in Apps (eg. service-a)
  - name: imageurl
    type: string
    description: Target container registry URL (eg. image-registry.openshift-image-registry.svc:5000/)
  - name: app-url
    type: string
    description: Git Repo URL for Apps (eg. https://github.com/tarosaiba/my-first-openshift-service-a.git)
  - name: app-revision
    type: string
    description: Git Repo Revision for Apps (eg. master)

  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.app-url)
    - name: revision
      value: $(params.app-revision)
    workspaces:
    - name: output
      workspace: app-code

  - name: build-container
    taskRef:
      name: kaniko
    runAfter:
    - git-clone
    workspaces:
    - name: source
      workspace: app-code
    params:
    - name: IMAGE
      value: $(params.imageurl)/$(params.target-app):$(params.app-revision)
    - name: CONTEXT
      value: $(params.target-app)/reviews-wlpcfg
    - name: BUILDER_IMAGE
      value: gcr.io/kaniko-project/executor@sha256:b9eec410fa32cd77cdb7685c70f86a96debb8b087e77e63d7fe37eaadb178709
      ##  description: kaniko v1.3.0

  - name: test-container
    taskRef:
      name: trivy
    runAfter:
    - build-container
    workspaces:
    - name: cache
      workspace: vul-cache
    params:
    - name: IMAGE
      value: $(params.imageurl)/$(params.target-app)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE-DIGEST)
