apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-small
  namespace: my-first-openshift-common
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
