kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-administrator-clusterrole
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: administrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
