# prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-my-first-openshift-operator-edit
  namespace: my-first-openshift-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: my-first-openshift-operator

# stg
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-my-first-openshift-operator-edit
  namespace: my-first-openshift-stg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: my-first-openshift-operator

# dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-my-first-openshift-operator-edit
  namespace: my-first-openshift-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: my-first-openshift-operator

# common
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-my-first-openshift-operator-edit
  namespace: my-first-openshift-common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: my-first-openshift-operator
