apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-openshift-stg
  namespace: openshift-gitops
  labels:
    environment: stg
spec:
  project: my-first-openshift
  destination:
    namespace: my-first-openshift-stg
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/stg
    repoURL: https://github.com/tarosaiba/my-first-openshift.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
