apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-first-openshift
  namespace: openshift-gitops
spec:
  description: My First OpenShift
  destinations:
  - namespace: my-first-openshift-dev
    server: https://kubernetes.default.svc
  - namespace: my-first-openshift-stg
    server: https://kubernetes.default.svc
  - namespace: my-first-openshift-prod
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: tekton.dev
    kind: '*'
  - group: triggers.tekton.dev
    kind: '*'
  sourceRepos:
  - https://github.com/tarosaiba/my-first-openshift.git
