# SCC Privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: my-first-openshift-common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: my-first-openshift-common

# Allows pulls from internal registry.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller-default
  namespace: my-first-openshift-common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-first-openshift-dev
- kind: ServiceAccount
  name: default
  namespace: my-first-openshift-stg
- kind: ServiceAccount
  name: default
  namespace: my-first-openshift-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller-privileged-app
  namespace: my-first-openshift-common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: privileged-app
  namespace: my-first-openshift-dev
- kind: ServiceAccount
  name: privileged-app
  namespace: my-first-openshift-stg
- kind: ServiceAccount
  name: privileged-app
  namespace: my-first-openshift-prod
