apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: my-first-openshift-dev
spec:
  description: Development Environment
  destinations:
  - namespace: my-openshift-dev
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: tekton.dev
    kind: '*'
  - group: triggers.tekton.dev
    kind: '*'
  sourceRepos:
  - https://github.com/tarosaiba/my-first-openshift.git
